config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  resources 'products'

  resources :projects do
    resources :kits
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kit.rb
class Kit < ApplicationRecord
  belongs_to :project
  has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  # t.string "part_number"
  # t.string "mfr_part_number"
  # t.integer "quantity"
  # t.string "pkg"
  # t.string "status"
  # t.string "type"
  validates :part_number, presence: true
  has_and_belongs_to_many :kits
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :kits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[show edit update destroy]
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show; end
  def edit; end

  def destroy
    return unless @product.destroy

    redirect_to products_path
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @product = Product.new article_params
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:products).permit(
      :part_number,
      :mfr_part_number,
      :quantity,
      :pkg,
      :status,
      :type
    )
  end

  def find_product
    @product = Product.find params[:id]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Captrack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Devise %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%# Devise %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
    <div>
    <% product.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :part_number %><br>
    <%= form.text_field :part_number %>
  </div>
  <div>
    <%= form.label :mfr_part_number %><br>
    <%= form.text_field :mfr_part_number %>
  </div>
  <div>
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity %>
  </div>
  <div>
    <%= form.label :pkg %><br>
    <%= form.text_field :pkg %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.text_field :status %>
  </div>
  <div>
    <%= form.label :type %><br>
    <%= form.text_field :type %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.part_number, product %>
    </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
    <%# t.string "part_number"
    t.string "mfr_part_number"
    t.integer "quantity"
    t.string "pkg"
    t.string "status"
    t.string "type" %>

<h1><%= @product.part_number %></h1>
<p><%= @product.mfr_part_number %></p>
<p><%= @product.quantity %></p>
<p><%= @product.pkg %></p>
<p><%= @product.status %></p>
<p><%= @product.type %></p>

<ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
</ul>
<ul>
  <li><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>